### ISSUE TITLE
Strategy for spawning & managing spot instances?

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/spring17-laravel-portal#7]

**Comment by mjaglan** [comment]
Taking this part.

**Comment by Ameya05** [comment]
@marpierc @smarru 
Hello professors, I was trying to set up an autoscale group in AWS, but looks like I do not have permissions to do so. I could configure the settings, but the AWS wizard fails when "Creating launch configuration           Failure"
I am also unable to see the AutoScaling group dashboard which leads me to believe it is a permission issue.

**Comment by Ameya05** [comment]
The Autoscale group is setup and running in Ohio.

One question which popped in my mind regarding spot instance is, considering the fact that these can get shutdown anytime and the Autoscale group will try to get another EC2 instance - 
**We need a way to initialize this newly spawned EC2 instance with our application.**

I know that on next deployment trigger, our application will get deployed to this instance. But prior to that we will be down 1 service inspite of having a Box up and running.

**Comment by anujbhan** [comment]
Use the userdata script

**Comment by mjaglan** [comment]
FYI. For reference: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html
